replicaCount: 1

image:
  repository: vladimirkhil/sistorageservice
  pullPolicy: IfNotPresent
  tag: 1.2.0
  nginxTag: "alpine"

nginxPrometheusExporter:
  tag: 0.11.0
  port: 9113
  resources: {}

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 5000
  targetPort: 8080
  nginxPort: 80
  nginxTargetPort: 80

ingress:
  enabled: false
  clientSecret: ''
  hosts: []
  tls: []

resources: {}
nginxResources: {}

volumePath: ''

maxUploadSize: '101m'
bodyBufferSize: '10m'

database:
  host: ''
  name: 'sistorage'
  user: 'postgres'
  passwordKey: ''
  passwordValue: 'postgres-password'

options:
  serveStaticFiles: false
  logLevel: Warning
  packageUri: ''
  logoUri: ''
  publicUri: ''
  otel:
    uri: 'http://localhost:4317'
    metric:
      exportInterval: 60000
