apiVersion: v1
entries:
  sistorage:
  - apiVersion: v2
    appVersion: 1.3.0
    created: "2024-08-04T13:50:48.3451977+02:00"
    description: A service for storing and searching for SIGame packages
    digest: b69396b2fe7432c5d9994bb89913fe2439590ed9c25ded39212639ac28c94801
    name: sistorage
    type: application
    urls:
    - sistorage-1.3.0.tgz
    version: 1.3.0
  - apiVersion: v2
    appVersion: 1.2.1
    created: "2024-08-04T13:50:48.3424557+02:00"
    description: A service for storing and searching for SIGame packages
    digest: e3822cb8368a12e8a284e7e85df6ea0e3954e130d4205023d0b2f44b2fcb814d
    name: sistorage
    type: application
    urls:
    - sistorage-1.2.1.tgz
    version: 1.2.1
  - apiVersion: v2
    appVersion: 1.2.0
    created: "2024-08-04T13:50:48.2729022+02:00"
    description: A service for storing and searching for SIGame packages
    digest: ab15dc38ee598ac6440dc676e4a2a0e3273b5ae18cb65cd77b76258f6adb231f
    name: sistorage
    type: application
    urls:
    - sistorage-1.2.0.tgz
    version: 1.2.0
  - apiVersion: v2
    appVersion: 1.1.2
    created: "2024-08-04T13:50:48.1960776+02:00"
    description: A service for storing and searching for SIGame packages
    digest: 537a3333c671cb858a49c7ebf5aa3ff826b529d626bfaab5001aa0328a91439c
    name: sistorage
    type: application
    urls:
    - sistorage-1.1.2.tgz
    version: 1.1.2
  - apiVersion: v2
    appVersion: 1.1.1
    created: "2024-08-04T13:50:48.1646604+02:00"
    description: A service for storing and searching for SIGame packages
    digest: 90e9fe9a921c034a3504699ea9db813f87d87f8e1b50d5944e584458c15d71c6
    name: sistorage
    type: application
    urls:
    - sistorage-1.1.1.tgz
    version: 1.1.1
  - apiVersion: v2
    appVersion: 1.1.0
    created: "2024-08-04T13:50:48.1316316+02:00"
    description: A service for storing and searching for SIGame packages
    digest: b6fbf9b226a4548e6e00dd3c0a546165fbb488f58636e096e0d652736f3a2ff3
    name: sistorage
    type: application
    urls:
    - sistorage-1.1.0.tgz
    version: 1.1.0
  - apiVersion: v2
    appVersion: 1.0.1
    created: "2024-08-04T13:50:48.1177867+02:00"
    description: A service for storing and searching for SIGame packages
    digest: 05aab546c2bbbd545af1e69f1bbec8ba8436cbc4b8d6334258775bd22fcb1424
    name: sistorage
    type: application
    urls:
    - sistorage-1.0.1.tgz
    version: 1.0.1
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2024-08-04T13:50:48.1079974+02:00"
    description: A service for storing and searching for SIGame packages
    digest: cf43e184f2ae1949a32aa8a16a89851a973c2b24c1cc912303f43e2ac5e39af6
    name: sistorage
    type: application
    urls:
    - sistorage-1.0.0.tgz
    version: 1.0.0
generated: "2024-08-04T13:50:48.0874894+02:00"
