apiVersion: v1
entries:
  sistorage:
  - apiVersion: v2
    appVersion: 1.1.1
    created: "2024-02-20T09:15:21.5592241+01:00"
    description: A service for storing and searching for SIGame packages
    digest: 90e9fe9a921c034a3504699ea9db813f87d87f8e1b50d5944e584458c15d71c6
    name: sistorage
    type: application
    urls:
    - sistorage-1.1.1.tgz
    version: 1.1.1
  - apiVersion: v2
    appVersion: 1.1.0
    created: "2024-02-20T09:15:21.558175+01:00"
    description: A service for storing and searching for SIGame packages
    digest: b6fbf9b226a4548e6e00dd3c0a546165fbb488f58636e096e0d652736f3a2ff3
    name: sistorage
    type: application
    urls:
    - sistorage-1.1.0.tgz
    version: 1.1.0
  - apiVersion: v2
    appVersion: 1.0.1
    created: "2024-02-20T09:15:21.5576547+01:00"
    description: A service for storing and searching for SIGame packages
    digest: 05aab546c2bbbd545af1e69f1bbec8ba8436cbc4b8d6334258775bd22fcb1424
    name: sistorage
    type: application
    urls:
    - sistorage-1.0.1.tgz
    version: 1.0.1
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2024-02-20T09:15:21.5470131+01:00"
    description: A service for storing and searching for SIGame packages
    digest: cf43e184f2ae1949a32aa8a16a89851a973c2b24c1cc912303f43e2ac5e39af6
    name: sistorage
    type: application
    urls:
    - sistorage-1.0.0.tgz
    version: 1.0.0
generated: "2024-02-20T09:15:21.5418288+01:00"
