apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "sistorage.fullname" . }}-secret
  labels:
    {{- include "sistorage.labels" . | nindent 4 }}
data:
  admin: {{ .Values.ingress.clientSecret | b64enc | quote }}