apiVersion: v1
kind: Service
metadata:
  name: {{ include "sistorage.fullname" . }}
  labels:
    {{- include "sistorage.labels" . | nindent 4 }}
    {{- if .Values.service.labels -}}
    {{- toYaml .Values.service.labels | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
    - port: {{ .Values.service.nginxPort }}
      targetPort: {{ .Values.service.nginxTargetPort }}
      protocol: TCP
      name: httpnginx
  selector:
    {{- include "sistorage.selectorLabels" . | nindent 4 }}
